# Generated by Django 4.0.4 on 2022-04-14 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Ebay', max_length=40)),
                ('description', models.TextField()),
                ('city', models.CharField(default='Amsterdam', max_length=40)),
                ('address', models.CharField(default='Switzerland', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Ebay', max_length=40)),
                ('description', models.TextField()),
                ('salary', models.IntegerField(max_length=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='api.company')),
            ],
        ),
    ]
